#!/usr/bin/env python3
"""Find files whose first 40 lines carry a 'generated' / 'DO NOT EDIT' marker."""
import os, re, sys
root = sys.argv[1]
EXTS = {".c", ".h", ".cc", ".cpp", ".hpp", ".ipp", ".def", ".inc", ".y", ".l"}
PAT = re.compile(r"(do not edit|don't edit|dont edit|generated by|auto[- ]?generated|automatically generated|this file is generated|generated file|@generated|code generated|generated from|generated with)", re.I)
SKIP = {".git"}
for dp, dns, fns in os.walk(root):
    dns[:] = [d for d in dns if d not in SKIP]
    for fn in fns:
        if os.path.splitext(fn)[1] not in EXTS:
            continue
        p = os.path.join(dp, fn)
        rel = os.path.relpath(p, root)
        if rel.startswith("tools/deploy") or rel.startswith("tools/obtest"):
            continue
        try:
            with open(p, encoding="utf-8", errors="replace") as f:
                lines = f.readlines()
        except OSError:
            continue
        for i, line in enumerate(lines[:40]):
            if PAT.search(line):
                print(f"{rel}\t{len(lines)}\tL{i+1}: {line.strip()[:110]}")
                break
