import subprocess, sys, re
R="/Users/colin/seekdb-dev/migrate-to-rust"
EXCL=[':!src/storage/fts/dict/ob_ik_dic.cpp', ':!src/oblib/common/timezone/ob_timezone_info.cpp',
      ':!src/oblib/lib/compress/zstd_1_3_8/zstd_src', ':!src/oblib/lib/codec/ob_generated_*',
      ':!src/oblib/grpc/*.pb.*', ':!src/share/geo/*.pb-c.*']
PATH=['src/*.h','src/*.hpp','src/*.cpp','src/*.cc','src/*.c','src/*.ipp']
def count(pat, extra=None):
    cmd=['git','-C',R,'grep','-c','-P',pat,'--']+PATH+EXCL
    out=subprocess.run(cmd,capture_output=True,text=True).stdout
    files=0; lines=0
    for l in out.splitlines():
        p,n=l.rsplit(':',1); files+=1; lines+=int(n)
    return lines,files
pats = {
 'virtual keyword': r'\bvirtual\b',
 'pure virtual (= 0)': r'\bvirtual\b[^;]*\)\s*(const\s*)?(noexcept\s*)?=\s*0\s*;',
 'override': r'\boverride\b',
 'dynamic_cast': r'\bdynamic_cast\s*<',
 'static_cast to pointer': r'static_cast\s*<\s*(const\s+)?[\w:]+(<[^>]*>)?\s*\*\s*>',
 'reinterpret_cast': r'\breinterpret_cast\s*<',
 'const_cast': r'\bconst_cast\s*<',
 'template< opening': r'^\s*template\s*<',
 'template<> specialization': r'template\s*<\s*>',
 'placement new (new (alloc) T)': r'\bnew\s*\(\s*[^)]+\)\s*[A-Za-z_:]',
 'explicit destructor call': r'(->|\.)~\w+\s*\(',
 'OB_NEW*': r'\bOB_NEW\w*\s*\(',
 'OB_FAIL(': r'\bOB_FAIL\s*\(',
 'OB_SUCC(': r'\bOB_SUCC\s*\(',
 'OB_SUCC(ret) && guard': r'\bOB_SUCC\s*\(\s*ret\s*\)\s*&&',
 'OB_ISNULL(': r'\bOB_ISNULL\s*\(',
 'OB_TMP_FAIL(': r'\bOB_TMP_FAIL\s*\(',
 'int tmp_ret = OB_SUCCESS;': r'\bint\s+tmp_ret\s*=\s*(common::)?OB_SUCCESS\s*;',
 'ret = OB_SUCCESS; reset': r'^\s*ret\s*=\s*(common::)?OB_SUCCESS\s*;',
 'OB_X == ret compare': r'\bOB_\w+\s*==\s*ret\b|\bret\s*==\s*OB_(?!SUCCESS)\w+',
 'int ret = OB_SUCCESS;': r'\bint\s+ret\s*=\s*(common::)?OB_SUCCESS\s*;',
 'int &ret = ..ret_;': r'\bint\s*&\s*ret\s*=\s*[\w.>-]*ret_\s*;',
 'union keyword': r'^\s*(typedef\s+)?union\b',
 'goto': r'\bgoto\s+\w+\s*;',
 'setjmp/longjmp family': r'\b(sig)?(setjmp|longjmp)\s*\(',
 'throw expression': r'^(?!\s*//).*\bthrow\s+[\w:]',
 'catch (': r'\bcatch\s*\(',
 'friend': r'^\s*friend\b',
 'operator overload (any)': r'\boperator\s*(==|!=|<=|>=|<<|>>|->|\+\+|--|\+=|-=|\*=|/=|&&|\|\||\[\]|\(\)|[-+*/%<>=&|^~!,])\s*\(',
 'operator() (functors)': r'\boperator\s*\(\s*\)\s*\(',
 'operator== ': r'\boperator\s*==\s*\(',
 'operator< ': r'\boperator\s*<\s*\(',
 'operator= (assignment)': r'\boperator\s*=\s*\(',
 'operator[] ': r'\boperator\s*\[\s*\]\s*\(',
 'operator<< ': r'\boperator\s*<<\s*\(',
 'operator new/delete': r'\boperator\s+(new|delete)\b',
 'operator bool/conversion': r'\boperator\s+(bool|int|int64_t|uint64_t|const\s+char\s*\*|char\s*\*)\s*\(',
 'default argument in decl (heuristic, .h only)': None,
 'SMART_CALL*': r'\bSMART_CALL\w*\s*\(',
 'ATOMIC_* macro call': r'\bATOMIC_[A-Z_0-9]+\s*\(',
 'std::atomic': r'std::atomic',
 'lib::ob_sort / ob_sort(': r'\bob_sort\s*\(',
 'std::sort(': r'\bstd::sort\s*\(',
 'std::stable_sort(': r'\bstd::stable_sort\s*\(',
 'lower_bound/upper_bound (std)': r'\bstd::(lower_bound|upper_bound|binary_search)\s*\(',
 'std::vector': r'\bstd::vector\s*<',
 'std::map/set/unordered': r'\bstd::(unordered_)?(map|set)\s*<',
 'std::string': r'\bstd::string\b',
 'std::function': r'\bstd::function\s*<',
 'std::shared_ptr/unique_ptr': r'\bstd::(shared|unique)_ptr\s*<',
 'std::variant/optional': r'\bstd::(variant|optional)\s*<',
 'pthread_ calls': r'\bpthread_\w+\s*\(',
 'std::thread': r'\bstd::thread\b',
 'co_await/co_yield/co_return': r'\bco_(await|yield|return)\b',
 'libaio io_ calls': r'\bio_(setup|submit|getevents|destroy|cancel)\s*\(',
 'mmap/munmap': r'\bm(un)?map\s*\(',
 '__int128': r'\b(__int128|int128_t|uint128_t|__uint128_t)\b',
 'alloca(': r'\balloca\s*\(',
 'va_list/va_start': r'\b(va_list|va_start)\b',
 '__builtin_expect / OB_LIKELY': r'\b(__builtin_expect|OB_LIKELY|OB_UNLIKELY)\s*\(',
 '#define (all)': r'^\s*#\s*define\b',
 'TO_STRING_KV': r'\bTO_STRING_KV\w*\s*\(',
 'OB_UNIS_VERSION*': r'\bOB_UNIS_VERSION\w*\s*\(',
 'OB_SERIALIZE_MEMBER*': r'\bOB_SERIALIZE_MEMBER\w*\s*\(',
 'LOG_WARN/LOG_INFO/etc': r'\b(LOG|SQL_LOG|STORAGE_LOG|COMMON_LOG|SERVER_LOG|OB_LOG|RS_LOG|SHARE_LOG|TRANS_LOG|PALF_LOG|CLOG_LOG|SHARE_SCHEMA_LOG|SQL_ENG_LOG|SQL_OPT_LOG|SQL_RESV_LOG|SQL_REWRITE_LOG|SQL_PC_LOG|PL_LOG|LIB_LOG|OBLOG_LOG|DDL_LOG)_(WARN|INFO|ERROR|TRACE|DEBUG|EDIAG|WDIAG|WARN_RET|ERROR_RET|INFO_RET|TRACE_RET|DEBUG_RET)\s*\(',
 'murmurhash': r'\bmurmurhash\w*\s*\(',
 'XXH64/XXH3/xxhash': r'\b(XXH64|XXH3_64bits|XXH32|xxhash\w*)\s*\(',
 'wyhash': r'\bwyhash\w*\s*\(',
 'ob_crc64 / crc64_sse42': r'\bob_crc64\w*\s*\(',
 'fnv_hash': r'\bfnv_hash\w*\s*\(',
 'std::hash': r'\bstd::hash\s*<',
 'compress()/compress2()/uncompress()': r'\b(compress2?|uncompress)\s*\(',
 'deflateInit/inflateInit': r'\b(deflateInit2?_?|inflateInit2?_?|deflate|inflate|deflateEnd|inflateEnd)\s*\(',
 'zlib crc32(': r'\bcrc32\s*\(',
 'ZSTD_ calls': r'\bZSTD_\w+\s*\(',
 'LZ4_ / snappy': r'\b(LZ4_\w+|snappy::\w+)\s*\(',
 'fma(': r'\bfmaf?\s*\(',
 '__attribute__((packed)) / pragma pack': r'__attribute__\s*\(\s*\(\s*packed|#\s*pragma\s+pack',
 'bitfield member': r'^\s*(unsigned|u?int(8|16|32|64)_t|bool|int|uint\d+_t|char)\s+\w+\s*:\s*\d+\s*;',
 'enum class': r'\benum\s+class\b',
 'plain enum': r'^\s*(typedef\s+)?enum\s+(?!class)\w*\s*(:\s*\w+)?\s*\{',
 'typedef': r'^\s*typedef\b',
 'using alias': r'^\s*using\s+\w+\s*=',
 'macro OB_SUCC def': None,
}
res=[]
for name,pat in pats.items():
    if pat is None: continue
    l,f=count(pat); res.append((name,l,f)); print(f"{name}\t{l}\t{f}", flush=True)
