#!/bin/bash
# Counts of the error idioms over src/ at 834bbee1e. Each line: label, count, command.
cd /Users/colin/seekdb-dev/migrate-to-rust
c() { printf "%-48s %8s   %s\n" "$1" "$(eval "$2" | wc -l | tr -d ' ')" "$2"; }
c "OB_FAIL( lines"                 "git grep -h 'OB_FAIL(' -- src"
c "OB_SUCC( lines"                 "git grep -h 'OB_SUCC(' -- src"
c "OB_SUCC(ret) && lines"          "git grep -h 'OB_SUCC(ret) &&' -- src"
c "OB_TMP_FAIL( lines"             "git grep -h 'OB_TMP_FAIL(' -- src"
c "tmp_ret lines (any)"            "git grep -h -w 'tmp_ret' -- src"
c "int tmp_ret = OB_SUCCESS; lines" "git grep -h 'int tmp_ret = OB_SUCCESS;' -- src"
c "OB_X == ret lines"              "git grep -h -E 'OB_[A-Z_0-9]+ == ret\b' -- src"
c "  of which OB_SUCCESS == ret"   "git grep -h -E 'OB_SUCCESS == ret\b' -- src"
c "  of which non-SUCCESS == ret"  "git grep -h -E 'OB_[A-Z_0-9]+ == ret\b' -- src | grep -v 'OB_SUCCESS == ret'"
c "ret == OB_X lines"              "git grep -h -E '\bret == OB_[A-Z_0-9]+' -- src"
c "OB_X != ret lines"              "git grep -h -E 'OB_[A-Z_0-9]+ != ret\b' -- src"
c "  of which OB_SUCCESS != ret"   "git grep -h -E 'OB_SUCCESS != ret\b' -- src"
c "ret = OB_SUCCESS; resets"       "git grep -h -E '\bret = OB_SUCCESS;' -- src"
c "  excluding declarations"       "git grep -h -E '\bret = OB_SUCCESS;' -- src | grep -v -E 'int (ret|tmp_ret) = OB_SUCCESS;'"
c "int ret = OB_SUCCESS; (function starts)" "git grep -h -E '\bint ret = OB_SUCCESS;' -- src"
c "int &ret = ret_; sites"         "git grep -n -E 'int\s*&\s*ret\s*=\s*ret_;' -- src"
c "int ret_; members"              "git grep -h -E '^\s*int\s+ret_;' -- src"
c "switch (ret) statements"        "git grep -h -E 'switch\s*\(\s*ret\s*\)' -- src"
c "K(ret) in log lines"            "git grep -h 'K(ret)' -- src"
c "LOG_WARN( lines"                "git grep -h 'LOG_WARN(' -- src"
c "LOG_USER_ERROR( lines"          "git grep -h 'LOG_USER_ERROR(' -- src"
c "LOG_USER_WARN( lines"           "git grep -h 'LOG_USER_WARN(' -- src"
c "LOG_USER_NOTE( lines"           "git grep -h 'LOG_USER_NOTE(' -- src"
c "FORWARD_USER_ERROR( lines"      "git grep -h 'FORWARD_USER_ERROR(' -- src"
c "FORWARD_USER_WARN( lines"       "git grep -h 'FORWARD_USER_WARN(' -- src"
c "FORWARD_USER_NOTE( lines"       "git grep -h 'FORWARD_USER_NOTE(' -- src"
c "LOG_USER_ERROR_LINE_COLUMN( lines" "git grep -h 'LOG_USER_ERROR_LINE_COLUMN(' -- src"
c "LOG_MYSQL_USER_ERROR( lines"    "git grep -h 'LOG_MYSQL_USER_ERROR(' -- src"
c "LOG_DBA_ERROR( lines"           "git grep -h 'LOG_DBA_ERROR(' -- src"
c "__USER_ERROR_MSG uses outside ob_errno.h" "git grep -h '__USER_ERROR_MSG' -- src ':!src/share/ob_errno.h' ':!src/share/gen_errno.pl' ':!src/oblib/lib/oblog/ob_log_module.h'"
c "ob_errpkt_errno( uses"          "git grep -h 'ob_errpkt_errno(' -- src ':!src/share/ob_errno.*'"
c "ob_sqlstate( uses"              "git grep -h 'ob_sqlstate(' -- src ':!src/share/ob_errno.*'"
c "ob_strerror( uses"              "git grep -h 'ob_strerror(' -- src ':!src/share/ob_errno.*'"
c "ob_str_user_error( uses"        "git grep -h 'ob_str_user_error(' -- src ':!src/share/ob_errno.*'"
c "ob_errpkt_strerror( uses"       "git grep -h 'ob_errpkt_strerror(' -- src ':!src/share/ob_errno.*'"
c "ob_errpkt_str_user_error( uses" "git grep -h 'ob_errpkt_str_user_error(' -- src ':!src/share/ob_errno.*'"
c "ob_error_name( uses"            "git grep -h 'ob_error_name(' -- src ':!src/share/ob_errno.*'"
c "ob_mysql_errno( uses"           "git grep -h -E 'ob_mysql_errno(_with_check)?\(' -- src ':!src/share/ob_errno.*'"
c "throw  statements in src"       "git grep -h -E '^\s*throw\b' -- src"
c "try { blocks in src"            "git grep -h -E '\btry\s*\{' -- src"
c "catch ( in src"                 "git grep -h -E '\bcatch\s*\(' -- src"
c "SMART_CALL( sites"              "git grep -h 'SMART_CALL(' -- src"
c "OB_SIZE_OVERFLOW total"         "git grep -h -w 'OB_SIZE_OVERFLOW' -- src"
c "ret_ member reads (ret_ word)"  "git grep -h -w 'ret_' -- src"
c "files with int ret_; member"    "git grep -l -E '^\s*int\s+ret_;' -- src"
c "error_ret_ uses"                "git grep -h -w 'error_ret_' -- src"
c "get_err_ret() uses"             "git grep -h 'get_err_ret()' -- src"
c "SQL_ENG_LOG/LOG_WARN with ret as value" "git grep -h -E 'LOG_(WARN|ERROR|INFO|TRACE|DEBUG)\(.*\bret\b' -- src"
c "COVER_SUCC( uses"               "git grep -h 'COVER_SUCC(' -- src"
c "OB_SUCCESS total tokens"        "git grep -h -w 'OB_SUCCESS' -- src"
c "files under src (tracked, code)" "git ls-files src | grep -E '\.(h|hpp|cpp|cc|c|ipp)$'"
